=== mornage/Maemo-pingus/doc/pingus-world.dtd
<!ELEMENT pingus-world (name,description-list,background,level-list)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name          
        xml:lang CDATA #REQUIRED>
<!ELEMENT description-list (description*)>

<!ELEMENT description (#PCDATA)>
<!ATTLIST description          
        xml:lang CDATA #REQUIRED>

<!ELEMENT background (surface)>
<!ELEMENT surface (resource)>

<!ELEMENT resource (resource-file, resource-ident)>
<!ELEMENT resource-file (#PCDATA)>
<!ELEMENT resource-ident (#PCDATA)>

<!ELEMENT level-list (level*)>
<!ELEMENT level (#PCDATA)>

=== mornage/Maemo-pingus/doc/worlds.xml
<?xml version="1.0"?>
<!DOCTYPE pingus-world SYSTEM "pingus-world.dtd">
  <pingus-world>
    <name xml:lang="en">Playable Levels</name>
    
  <description-list>
    <description xml:lang="en">
      When we have enough, these levels will be
      catagorised into worlds. More levels are very welcome.
    </description>
    
    <description xml:lang="de_DE">
      Wenn genügend spielbare Level vorhanden sind wird das hier
      etwas aufgeraeumt und die Level bekommen jeweils ihre eigene
      Welt.
    </description>
  </description-list>
  
  <background>
    <surface><resource>
	<resource-file>textures.dat</resource-file>
	<resource-ident>Textures/stars</resource-ident>
      </resource></surface>
  </background>
  
  <level-list>
    <level>longway.plf</level>
    <level>rinse.plf</level>
    <level>Lev4.plf</level>
    <level>Wland.plf</level>
    <level>particle.plf</level>
    <level>Stair.plf</level>
    <level>cages.plf</level>
    <level>partic2.plf</level>
    <level>jewel.plf</level>
    <level>bombing.plf</level>
  </level-list>
  
</pingus-world>

<!-- EOF -->
